### ISSUE TITLE
Is there a way to add more ports to the network section of the configuration page?

### ISSUE THREAD

**Issue by ZEi20T** [hassio-addons/addon-nginx-proxy-manager#590] opened 2024-07-25 06:41 UTC
# Problem/Motivation

> Looking to leverage Streams

## Expected behavior

> Configured ports exposed to the host

## Actual behavior

> Ports remain closed

## Steps to reproduce

> Configure any port forward in Streams

## Proposed changes

> Please add more ports to the network configuration so we can leverage Streams :)

**Comment by tjorim** [comment] 2024-07-25 08:35
No, there is no way. Duplicate of https://github.com/hassio-addons/addon-nginx-proxy-manager/issues/553.

**Closed by tjorim** 2024-07-25 08:35 UTC
