### ISSUE TITLE
NPM seemingly lost settings/logins, yet still works with proxy hosts and SSL certificates.

### ISSUE THREAD

**Issue by jasauders** [hassio-addons/addon-nginx-proxy-manager#359] opened 2022-09-19 12:50 UTC
# Problem/Motivation

> I logged into NPM within Home Assistant and received the error "no relevant user found". I always set up two user accounts out of precaution, yet, both yielded the same error.

## Expected behavior

> I expected to be able to log in to see my dashboard.

## Actual behavior

> It seems to be working from a clean slate, as admin@example.com/changeme is the only one that worked. Oddly, if I stop MariaDB from within Home Assistant, NPM begins to fail to serve me my existing proxy hosts/SSL certificates. If I start MariaDB, NPM begins to work with those again. It seems clear that MariaDB is playing an active role with NPM's ability to serve existing proxy hosts/SSL certificates despite my inability to log in to the dashboard. If I work through the "new user" setup using admin@example.com/changeme (the only account that responds in any meaningful way), I'm presented with 0 hosts, 0 certificates, basically as if it's a clean slate. Somewhere my current config is living and active as otherwise I wouldn't have functional certs/hosts, but I just have no idea where it's working from.

## Steps to reproduce

> Unfortunately I have no idea. I don't need to check NPM on a consistent basis as it just kind of works. The only thing that has changed recently is updates were installed to Home Assistant Supervisor/Core, but I have no clue if that would have impacted this situation.

## Proposed changes

> Perhaps this exists and I'm not aware of how -- but the ability to dig into the database settings and even re-bind it to NPM dashboard in an effort to reestablish the settings and connections.

**Comment by tjorim** [comment] 2022-09-19 13:58
Duplicate of #344.

**Closed** 2022-09-19 13:58 UTC
