### ISSUE TITLE
HTTP integration is not set-up for reverse proxies

### ISSUE THREAD

**Issue by doosterkamp** [hassio-addons/addon-nginx-proxy-manager#229] opened 2021-06-04 13:14 UTC
# Problem/Motivation

The core-log is being 'spammed' with a warning (one entry on almost every request) after updating HA Core to 2021.6.x:
```
WARNING (MainThread) [homeassistant.components.http.forwarded] A request from a reverse proxy was received from 172.30.33.5, but your HTTP integration is not set-up for reverse proxies; This request will be blocked in Home Assistant 2021.7 unless you configure your HTTP integration to allow this header
```
(With ```172.30.33.5``` being the container running this addon on a Supervised HA setup (Intel NUC))

Everything seems to be working as expected, but my worry is now it will stop working on the next major release (2021.7.x)

## Expected behavior

A clean log

## Actual behavior

A very polluted log

## Steps to reproduce

- I updated HA core from the latest 2021.5 to 2021.6.1

## Proposed changes

?

**Comment by sinclairpaul** [comment] 2021-06-04 13:34
Duplicate of #228 

This is a Home Assistant configuration issue, not the addon.  Documentation can be found at https://www.home-assistant.io/integrations/http/

**Closed by sinclairpaul** 2021-06-04 13:34 UTC
