### ISSUE TITLE
Internal Error on create a new SSL cert

### ISSUE THREAD

**Issue by flipepiloto** [hassio-addons/addon-nginx-proxy-manager#91] opened 2020-05-06 18:38 UTC
# Problem / Motivation

Internal error when creating a new SSL certificate

## Expected behavior

The creation of the SSL certificate

## Real behavior

Internal error when creating a new SSL certificate

## Steps to reproduce

1 - Create on my router a port targeting the 80 external to 80 internal and 443 external to 443 internal.
2 - Install the Nginx Proxy Manager Addon and start
3 - Create a host as it says in the manual and I created a creation then SSL, for example, an internal error and the log below

[5/6/2020] [2:50:27 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[5/6/2020] [2:50:27 PM] [SSL      ] › ℹ  info      Requesting Let'sEncrypt certificates for Cert #10: xyz.duckdns.org
[5/6/2020] [2:50:50 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[5/6/2020] [2:50:50 PM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-10" --agree-tos --email "xyz@gmail.com" --preferred-challenges "dns,http" --webroot --domains "xyz.duckdns.org" 
Saving debug log to /data/logs/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for xyz.duckdns.org
Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
Waiting for verification...
Challenge failed for domain xyz.duckdns.org
http-01 challenge for xyz.duckdns.org
Cleaning up challenges
Some challenges have failed.

## Proposed changes

Need help.

**Comment by flipepiloto** [comment] 2020-05-06 18:50
![erro](https://user-images.githubusercontent.com/63123077/81216457-4d794d00-8fb1-11ea-90e2-16be7d3784d2.jpg)
I also tried to reverse the order of execution, first creating the SSL certificate and then creating the host linking the two, but the host went offline and with the log below.

**Comment by sinclairpaul** [comment] 2020-05-06 19:32
Have you confirmed that the external port is open and working?  You should be able to access your external address (from an external source) on 80 and receive a default page, or at least an entry in the log.

**Comment by pratik5705** [comment] 2020-05-19 19:04
I am getting the exact same error. External port is open and working. I am able to get to the hass login page from an external source.

**Comment by Thumbleweed** [comment] 2020-05-21 09:09
I'm having the exact same issue.

**Comment by tinglis1** [comment] 2020-05-27 01:10
I have the same issue. I am currently using the "custom" ssl certificate and using the files generated for the duckdns addon.
This issue also appears on the NPM github.
https://github.com/jc21/nginx-proxy-manager/issues/180#

**Comment by Domy5** [comment] 2020-05-30 03:18
same issue

**Comment by frenck** [comment] 2020-05-30 08:28
This is always either of the following:

- You haven't correctly set up port forwarding from your router on port 80 & 443. Your SSL cert creation will fail if you didn't do that right.
- Your provider doesn't allow for opening up port 443 or 80. This means this add-on is not for you.
- You are behind a GCNAT, sorry to hear that. This add-on is not for you.

**Comment by frenck** [comment] 2020-05-30 15:20
Duplicate of #69

**Closed by frenck** 2020-05-30 15:20 UTC
