### ISSUE TITLE
[Global   ] › ✖  error     Cannot find module '../global/certbot-dns-plugins'

### ISSUE THREAD

**Issue by supersonical** [hassio-addons/addon-nginx-proxy-manager#118] opened 2020-10-24 21:10 UTC
# Problem/Motivation

> (Why the issue was filed)

Stuck in somekind of bootloop

> (What you expected to happen)

Start up normally

> (What actually happened)

Installed latest version

> (How can someone else make/see it happen)
Install latest version

[23:08:23] INFO: Starting the Manager...
[10/24/2020] [11:08:24 PM] [Global   ] › ✖  error     Cannot find module '../global/certbot-dns-plugins'
Require stack:
- /opt/nginx-proxy-manager/internal/certificate.js
- /opt/nginx-proxy-manager/internal/proxy-host.js
- /opt/nginx-proxy-manager/internal/report.js
- /opt/nginx-proxy-manager/routes/api/reports.js
- /opt/nginx-proxy-manager/routes/api/main.js
- /opt/nginx-proxy-manager/app.js
- /opt/nginx-proxy-manager/index.js Error: Cannot find module '../global/certbot-dns-plugins'
Require stack:
- /opt/nginx-proxy-manager/internal/certificate.js
- /opt/nginx-proxy-manager/internal/proxy-host.js
- /opt/nginx-proxy-manager/internal/report.js
- /opt/nginx-proxy-manager/routes/api/reports.js
- /opt/nginx-proxy-manager/routes/api/main.js
- /opt/nginx-proxy-manager/app.js
- /opt/nginx-proxy-manager/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/nginx-proxy-manager/internal/certificate.js:16:26)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/nginx-proxy-manager/internal/certificate.js',
    '/opt/nginx-proxy-manager/internal/proxy-host.js',
    '/opt/nginx-proxy-manager/internal/report.js',
    '/opt/nginx-proxy-manager/routes/api/reports.js',
    '/opt/nginx-proxy-manager/routes/api/main.js',
    '/opt/nginx-proxy-manager/app.js',
    '/opt/nginx-proxy-manager/index.js'
  ]
}
[23:08:24] INFO: Starting the Manager...
[10/24/2020] [11:08:26 PM] [Global   ] › ✖  error     Cannot find module '../global/certbot-dns-plugins'
Require stack:
- /opt/nginx-proxy-manager/internal/certificate.js
- /opt/nginx-proxy-manager/internal/proxy-host.js
- /opt/nginx-proxy-manager/internal/report.js
- /opt/nginx-proxy-manager/routes/api/reports.js
- /opt/nginx-proxy-manager/routes/api/main.js
- /opt/nginx-proxy-manager/app.js
- /opt/nginx-proxy-manager/index.js Error: Cannot find module '../global/certbot-dns-plugins'
Require stack:
- /opt/nginx-proxy-manager/internal/certificate.js
- /opt/nginx-proxy-manager/internal/proxy-host.js
- /opt/nginx-proxy-manager/internal/report.js
- /opt/nginx-proxy-manager/routes/api/reports.js
- /opt/nginx-proxy-manager/routes/api/main.js
- /opt/nginx-proxy-manager/app.js
- /opt/nginx-proxy-manager/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/nginx-proxy-manager/internal/certificate.js:16:26)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/nginx-proxy-manager/internal/certificate.js',
    '/opt/nginx-proxy-manager/internal/proxy-host.js',
    '/opt/nginx-proxy-manager/internal/report.js',
    '/opt/nginx-proxy-manager/routes/api/reports.js',
    '/opt/nginx-proxy-manager/routes/api/main.js',
    '/opt/nginx-proxy-manager/app.js',
    '/opt/nginx-proxy-manager/index.js'
  ]
}

**Comment by moto3001** [comment] 2020-10-24 21:18
I'm experiencing the same, so I just rolled back to 0.7.0.

**Comment by supersonical** [comment] 2020-10-24 21:21
How did you rollbaack?

**Comment by moto3001** [comment] 2020-10-24 21:22
I restored just the add-on from a previous backup.

**Comment by frenck** [comment] 2020-10-24 21:51
Duplicate of #117

**Closed by frenck** 2020-10-24 21:51 UTC
