### ISSUE TITLE
NGINX does not start from yesterday's update

### ISSUE THREAD

**Issue by dziobson** [hassio-addons/addon-nginx-proxy-manager#121] opened 2020-10-25 08:51 UTC
This is my log

[10/25/2020] [8:50:35 AM] [Global   ] › ✖  error     Cannot find module '../global/certbot-dns-plugins'
Require stack:
- /opt/nginx-proxy-manager/internal/certificate.js
- /opt/nginx-proxy-manager/internal/proxy-host.js
- /opt/nginx-proxy-manager/internal/report.js
- /opt/nginx-proxy-manager/routes/api/reports.js
- /opt/nginx-proxy-manager/routes/api/main.js
- /opt/nginx-proxy-manager/app.js
- /opt/nginx-proxy-manager/index.js Error: Cannot find module '../global/certbot-dns-plugins'
Require stack:
- /opt/nginx-proxy-manager/internal/certificate.js
- /opt/nginx-proxy-manager/internal/proxy-host.js
- /opt/nginx-proxy-manager/internal/report.js
- /opt/nginx-proxy-manager/routes/api/reports.js
- /opt/nginx-proxy-manager/routes/api/main.js
- /opt/nginx-proxy-manager/app.js
- /opt/nginx-proxy-manager/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/nginx-proxy-manager/internal/certificate.js:16:26)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/nginx-proxy-manager/internal/certificate.js',
    '/opt/nginx-proxy-manager/internal/proxy-host.js',
    '/opt/nginx-proxy-manager/internal/report.js',
    '/opt/nginx-proxy-manager/routes/api/reports.js',
    '/opt/nginx-proxy-manager/routes/api/main.js',
    '/opt/nginx-proxy-manager/app.js',
    '/opt/nginx-proxy-manager/index.js'
  ]
}

and so it repeats itself all the time

**Comment by frenck** [comment] 2020-10-25 09:33
Duplicate of #117

**Closed by frenck** 2020-10-25 09:33 UTC
