### ISSUE TITLE
502 /api/tokens

### ISSUE THREAD

**Issue by henrikhjelm** [hassio-addons/addon-nginx-proxy-manager#119] opened 2020-10-24 21:48 UTC
# Problem/Motivation
when i am trying to login after update in home assistant i get a 
Error 502 (bad gateway) on /api/tokens  .
and the text Bad "Gateway" in the form
![Screenshot (17)](https://user-images.githubusercontent.com/5031424/97094226-4b847280-1653-11eb-9fe3-e3540d1b4904.png)

**Comment by tiberiushunter** [comment] 2020-10-24 21:54
I'm currently getting this too (after going to v0.8.0) in your logs do you get the error I've got? https://github.com/hassio-addons/addon-nginx-proxy-manager/issues/117

Looks like @frenck is on it if that is the case 👍🏻

**Comment by henrikhjelm** [comment] 2020-10-24 21:55
and the bootloop i belive it is from " https://github.com/hassio-addons/addon-nginx-proxy-manager/issues/117 "
![Screenshot (18)](https://user-images.githubusercontent.com/5031424/97094316-4aa01080-1654-11eb-96fb-96258f7fcd57.png)

**Comment by frenck** [comment] 2020-10-25 09:33
Duplicate of #117

**Closed by frenck** 2020-10-25 09:33 UTC
